#!/usr/bin/env python3
"""Generate one native x86 FMA fixture per manifest mnemonic."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "tests/integration/latx-avx-opt-only-manifest.json"
INTEGRATION = ROOT / "tests/integration"


def fma_entries() -> list[str]:
    manifest = json.loads(MANIFEST.read_text())
    return [entry["mnemonic"] for entry in manifest["entries"]
            if entry["category"] == "fma"]


def packed(mnemonic: str) -> bool:
    return mnemonic.endswith(("ps", "pd"))


def assembly(mnemonic: str) -> str:
    vector = "ymm" if packed(mnemonic) else "xmm"
    load = "vmovdqu" if packed(mnemonic) else "movdqu"
    width = 32 if packed(mnemonic) else 16
    return f'''/* generated by generate-latx-avx-fma-fixtures.py */
    .intel_syntax noprefix
    .text
    .globl latx_avx_single_fma_run
    .type latx_avx_single_fma_run, @function
latx_avx_single_fma_run:
    cmp edx, 1
    je .Lmemory
    cmp edx, 2
    je .Lalias_vvvv
    cmp edx, 3
    je .Lalias_rm
    {load} {vector}0, [rsi]
    {load} {vector}1, [rsi + 32]
    {load} {vector}2, [rsi + 64]
    {mnemonic} {vector}0, {vector}1, {vector}2
    jmp .Lstore
.Lmemory:
    {load} {vector}0, [rsi]
    {load} {vector}1, [rsi + 32]
    {mnemonic} {vector}0, {vector}1, [rsi + 96]
    jmp .Lstore
.Lalias_vvvv:
    {load} {vector}0, [rsi]
    {load} {vector}2, [rsi + 64]
    {mnemonic} {vector}0, {vector}0, {vector}2
    jmp .Lstore
.Lalias_rm:
    {load} {vector}0, [rsi]
    {load} {vector}1, [rsi + 32]
    {mnemonic} {vector}0, {vector}1, {vector}0
.Lstore:
    {load} [rdi], {vector}0
    stmxcsr [rdi + 32]
    ret
.size latx_avx_single_fma_run, .-latx_avx_single_fma_run

    .section .note.GNU-stack,"",@progbits
'''


def c_source(mnemonic: str) -> str:
    return f'''/* generated by generate-latx-avx-fma-fixtures.py */
#include "latx-avx-single-common.h"

extern void latx_avx_single_fma_run(uint8_t *, const uint8_t *, int);

static const uint64_t input[64] = {{
    UINT64_C(0x400000003f800000), UINT64_C(0x4080000040400000),
    UINT64_C(0x4100000040c00000), UINT64_C(0x4180000041400000),
    UINT64_C(0x3ff0000000000000), UINT64_C(0x4008000000000000),
    UINT64_C(0x4014000000000000), UINT64_C(0x401c000000000000),
    UINT64_C(0x3ff0000000000000), UINT64_C(0x4000000000000000),
    UINT64_C(0x4008000000000000), UINT64_C(0x4010000000000000),
    UINT64_C(0x3ff0000000000000), UINT64_C(0x4000000000000000),
    UINT64_C(0x4008000000000000), UINT64_C(0x4010000000000000),
    UINT64_C(0x8000000000000000), UINT64_C(0x7ff0000000000000),
    UINT64_C(0x0000000000000001), UINT64_C(0x7ff8000000001234),
    UINT64_C(0x8000000000000000), UINT64_C(0xfff0000000000000),
    UINT64_C(0x8000000000000001), UINT64_C(0xfff8000000005678),
    UINT64_C(0x0010000000000000), UINT64_C(0x7fefffffffffffff),
    UINT64_C(0x0000000000000001), UINT64_C(0x0010000000000000),
    UINT64_C(0x3ff0000000000001), UINT64_C(0xbff0000000000001),
    UINT64_C(0x3fefffffffffffff), UINT64_C(0xbfefffffffffffff),
    UINT64_C(0x3ff0000000000000), UINT64_C(0xc000000000000000),
    UINT64_C(0x4000000000000000), UINT64_C(0x3fd0000000000000),
    UINT64_C(0x3ff8000000000000), UINT64_C(0x3fe0000000000000),
    UINT64_C(0x4004000000000000), UINT64_C(0x3fd5555555555555),
    UINT64_C(0x7ff0000000000000), UINT64_C(0x0000000000000000),
    UINT64_C(0xfff0000000000000), UINT64_C(0x8000000000000000),
    UINT64_C(0x7ff8000000001234), UINT64_C(0x7ff0000000001234),
    UINT64_C(0xfff8000000005678), UINT64_C(0xfff0000000005678),
    UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000),
    UINT64_C(0x4000000000000000), UINT64_C(0x4000000000000000),
    UINT64_C(0x3ff0000000000001), UINT64_C(0x3ff0000000000001),
    UINT64_C(0x3fe0000000000000), UINT64_C(0x3fe0000000000000),
    UINT64_C(0x0000000000000001), UINT64_C(0x0000000000000001),
    UINT64_C(0x7fefffffffffffff), UINT64_C(0x7fefffffffffffff),
    UINT64_C(0x3ff8000000000000), UINT64_C(0x4000000000000000),
    UINT64_C(0x4004000000000000), UINT64_C(0x4008000000000000),
}};

static int same(const char *left, const char *right)
{{
    while (*left != '\\0' && *left == *right) {{
        ++left;
        ++right;
    }}
    return *left == *right;
}}

int latx_avx_single_main(long argc, char **argv)
{{
    static uint8_t output[4 * 40];
    const char *mode = argc > 1 ? argv[1] : "reference";
    int base = same(mode, "special") ? 16 :
               same(mode, "snan") ? 40 :
               same(mode, "rounding") ? 48 : 0;

    for (int case_id = 0; case_id < 4; ++case_id) {{
        latx_avx_single_fma_run(output + case_id * 40,
                                (const uint8_t *)input + base * 8,
                                case_id);
    }}
    return latx_avx_single_write_all(output, sizeof(output)) != 0;
}}

/* fixture mnemonic: {mnemonic} */
'''


def wrapper(mnemonic: str) -> str:
    return f'''#!/bin/sh
set -eu
exec "$(dirname "$0")/build-latx-avx-fma-xzy86.sh" {mnemonic} "$@"
'''


def check() -> None:
    entries = fma_entries()
    missing = []
    for mnemonic in entries:
        for suffix in (".S", ".c"):
            if not (INTEGRATION / f"latx-avx-single-{mnemonic}{suffix}").is_file():
                missing.append(mnemonic + suffix)
        if not (INTEGRATION / f"test-latx-avx-single-{mnemonic}.sh").is_file():
            missing.append(mnemonic + ".sh")
    if missing:
        raise SystemExit("missing FMA fixtures: " + ", ".join(missing))
    print(f"PASS FMA fixture inventory: {len(entries)} independent mnemonics")


def generate() -> None:
    for mnemonic in fma_entries():
        stem = INTEGRATION / f"latx-avx-single-{mnemonic}"
        (stem.with_suffix(".S")).write_text(assembly(mnemonic))
        (stem.with_suffix(".c")).write_text(c_source(mnemonic))
        runner = INTEGRATION / f"test-latx-avx-single-{mnemonic}.sh"
        runner.write_text(wrapper(mnemonic))
        runner.chmod(0o755)
    print(f"PASS generated FMA fixtures: {len(fma_entries())}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--generate", action="store_true")
    args = parser.parse_args()
    if args.generate:
        generate()
    if args.check or not args.generate:
        check()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
