/* generated by generate-latx-avx-fma-fixtures.py */
#include "latx-avx-single-common.h"

extern void latx_avx_single_fma_run(uint8_t *, const uint8_t *, int);

static const uint64_t input[64] = {
    UINT64_C(0x400000003f800000), UINT64_C(0x4080000040400000),
    UINT64_C(0x4100000040c00000), UINT64_C(0x4180000041400000),
    UINT64_C(0x3ff0000000000000), UINT64_C(0x4008000000000000),
    UINT64_C(0x4014000000000000), UINT64_C(0x401c000000000000),
    UINT64_C(0x3ff0000000000000), UINT64_C(0x4000000000000000),
    UINT64_C(0x4008000000000000), UINT64_C(0x4010000000000000),
    UINT64_C(0x3ff0000000000000), UINT64_C(0x4000000000000000),
    UINT64_C(0x4008000000000000), UINT64_C(0x4010000000000000),
    UINT64_C(0x8000000000000000), UINT64_C(0x7ff0000000000000),
    UINT64_C(0x0000000000000001), UINT64_C(0x7ff8000000001234),
    UINT64_C(0x8000000000000000), UINT64_C(0xfff0000000000000),
    UINT64_C(0x8000000000000001), UINT64_C(0xfff8000000005678),
    UINT64_C(0x0010000000000000), UINT64_C(0x7fefffffffffffff),
    UINT64_C(0x0000000000000001), UINT64_C(0x0010000000000000),
    UINT64_C(0x3ff0000000000001), UINT64_C(0xbff0000000000001),
    UINT64_C(0x3fefffffffffffff), UINT64_C(0xbfefffffffffffff),
    UINT64_C(0x3ff0000000000000), UINT64_C(0xc000000000000000),
    UINT64_C(0x4000000000000000), UINT64_C(0x3fd0000000000000),
    UINT64_C(0x3ff8000000000000), UINT64_C(0x3fe0000000000000),
    UINT64_C(0x4004000000000000), UINT64_C(0x3fd5555555555555),
    UINT64_C(0x7ff0000000000000), UINT64_C(0x0000000000000000),
    UINT64_C(0xfff0000000000000), UINT64_C(0x8000000000000000),
    UINT64_C(0x7ff8000000001234), UINT64_C(0x7ff0000000001234),
    UINT64_C(0xfff8000000005678), UINT64_C(0xfff0000000005678),
    UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000),
    UINT64_C(0x4000000000000000), UINT64_C(0x4000000000000000),
    UINT64_C(0x3ff0000000000001), UINT64_C(0x3ff0000000000001),
    UINT64_C(0x3fe0000000000000), UINT64_C(0x3fe0000000000000),
    UINT64_C(0x0000000000000001), UINT64_C(0x0000000000000001),
    UINT64_C(0x7fefffffffffffff), UINT64_C(0x7fefffffffffffff),
    UINT64_C(0x3ff8000000000000), UINT64_C(0x4000000000000000),
    UINT64_C(0x4004000000000000), UINT64_C(0x4008000000000000),
};

static int same(const char *left, const char *right)
{
    while (*left != '\0' && *left == *right) {
        ++left;
        ++right;
    }
    return *left == *right;
}

int latx_avx_single_main(long argc, char **argv)
{
    static uint8_t output[4 * 40];
    const char *mode = argc > 1 ? argv[1] : "reference";
    int base = same(mode, "special") ? 16 :
               same(mode, "snan") ? 40 :
               same(mode, "rounding") ? 48 : 0;

    for (int case_id = 0; case_id < 4; ++case_id) {
        latx_avx_single_fma_run(output + case_id * 40,
                                (const uint8_t *)input + base * 8,
                                case_id);
    }
    return latx_avx_single_write_all(output, sizeof(output)) != 0;
}

/* fixture mnemonic: vfnmadd231sd */
