#!/bin/sh
set -eu
script_dir=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
fault_cases='xmm-cross-1 xmm-cross-15 ymm-cross-1 ymm-cross-15 ymm-cross-16 ymm-cross-31'
usage() { echo "usage: $0 generate PROBE OUTPUT_DIR" >&2; echo "       $0 verify LATX_X86_64 PROBE EXPECTED_DIR SOURCE" >&2; exit 2; }
check_probe() { if [ "${LATX_AVX_SKIP_PROBE_CHECK:-0}" = 1 ]; then echo "SKIP single AVX mnemonic check: x86 objdump unavailable"; else "$script_dir/check-latx-avx-single-mnemonic.sh" "$1" vxorpd; fi; }
run_case() { runner=$1 probe=$2 name=$3 output=$4 status_file=$5 error=$6; set +e; if [ -n "$runner" ]; then env LATX_AVX_CPUID=0 LATX_AOT=0 LATX_AVX_TRACE=3 LATX_AVX_TRACE_YMM=15 LATX_AVX_TRACE_YMM_INIT=1 "$runner" "$probe" "$name" >"$output" 2>"$error"; else "$probe" "$name" >"$output" 2>"$error"; fi; status=$?; set -e; printf '%s\n' "$status" >"$status_file"; }
normalise_trace_reference() { od -An -v -tx8 -w64 "$1" | awk -v reg="$2" 'NR <= 20 { target0 = ((NR - 1) % 10) < 5 } NR > 20 { target0 = (((NR - 21) % 32) % 4) < 2 } { target = (reg == 0) ? target0 : !target0; if (target) print $1, $2, $3, $4; else print $5, $6, $7, $8 }'; }
marker() { nm -n "$1" | awk '$3 == "latx_avx_single_vxorpd_observe_marker" { sub(/^0+/, "", $1); print "0x" $1 }'; }
trace_state() { awk -v marker="$2" '/event=hit/ { capture=saw; saw=index($0,"pc=" marker " ") != 0; next } capture && /event=ymm_state/ { for(i=1;i<=NF;i++){split($i,f,"=");if(f[1]=="low0")a=f[2];if(f[1]=="low1")b=f[2];if(f[1]=="shadow_high0")c=f[2];if(f[1]=="shadow_high1")d=f[2]} print a,b,c,d; capture=0 }' "$1"; }
check_fault() { [ "$(sed -n '1p' "$2")" = 139 ] || { echo "FAIL fault status" >&2; exit 1; }; [ "$(wc -c <"$1")" = 48 ] || { echo "FAIL fault record size" >&2; exit 1; }; [ "$(od -An -v -tx4 -N8 "$1" | tr -d ' \n')" = 0000000b00000002 ] || { echo "FAIL fault signal/code" >&2; exit 1; }; [ "$(od -An -v -tu8 -j8 -N8 "$1" | tr -d ' \n')" = 4096 ] || { echo "FAIL fault offset" >&2; exit 1; }; }
check_source() { body=$(awk '/bool translate_vxorpd\(/ { f=1 } f { print } f && /^}/ { exit }' "$1"); printf '%s\n' "$body" | grep -Fq 'if (1)'; printf '%s\n' "$body" | grep -Fq 'load_v128_from_ir1_mem_exact'; printf '%s\n' "$body" | grep -Fq 'load_v256_from_ir1_mem_exact'; printf '%s\n' "$body" | grep -Fq 'clear_ymm_high128_shadow'; printf '%s\n' "$body" | grep -Fq 'load_ymm_high128_shadow'; printf '%s\n' "$body" | grep -Fq 'store_ymm_high128_shadow'; lsx=$(printf '%s\n' "$body" | awk '/if \(1\)/ { f=1 } f && /} else {/ { exit } f { print }'); if printf '%s\n' "$lsx" | grep -Eq '\bla_xv'; then echo "FAIL vxorpd LSX branch contains LASX" >&2; exit 1; fi; }
check_host() { dump=$(objdump -d "$1" | awk '/<translate_vxorpd>:/ { f=1 } f { print } f && /^$/ { exit }'); if printf '%s\n' "$dump" | grep -Eq '<la_xv[^>]*>'; then echo "FAIL compiled vxorpd calls LASX generator" >&2; exit 1; fi; printf '%s\n' "$dump" | grep -Fq '<la_vxor_v>'; printf '%s\n' "$dump" | grep -Fq '<load_v128_from_ir1_mem_exact>'; printf '%s\n' "$dump" | grep -Fq '<load_v256_from_ir1_mem_exact>'; printf '%s\n' "$dump" | grep -Fq '<clear_ymm_high128_shadow>'; printf '%s\n' "$dump" | grep -Fq '<store_ymm_high128_shadow>'; }
case "${1-}" in
generate) [ "$#" = 3 ] || usage; probe=$2; expected=$3; mkdir -p "$expected"; check_probe "$probe"; "$probe" reference >"$expected/reference.bin"; [ "$(wc -c <"$expected/reference.bin")" = 5376 ] || { echo "FAIL reference output size" >&2; exit 1; }; normalise_trace_reference "$expected/reference.bin" 0 >"$expected/state-ymm0.txt"; normalise_trace_reference "$expected/reference.bin" 15 >"$expected/state-ymm15.txt"; [ "$(wc -l <"$expected/state-ymm0.txt")" = 84 ] || { echo "FAIL reference state count" >&2; exit 1; }; for n in $fault_cases; do run_case '' "$probe" "$n" "$expected/$n.bin" "$expected/$n.status" "$expected/$n.stderr"; check_fault "$expected/$n.bin" "$expected/$n.status"; done; echo "PASS generated x86 vxorpd reference";;
verify) [ "$#" = 5 ] || usage; latx=$2; probe=$3; expected=$4; source=$5; tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT HUP INT TERM; check_probe "$probe"; pc=$(marker "$probe"); [ -n "$pc" ] || { echo "FAIL missing vxorpd observer marker" >&2; exit 1; }; for reg in 0 15; do env LATX_AVX_CPUID=0 LATX_AOT=0 LATX_AVX_TRACE=3 LATX_AVX_TRACE_YMM="$reg" LATX_AVX_TRACE_YMM_INIT=1 "$latx" "$probe" trace >"$tmp/trace-$reg.out" 2>"$tmp/trace-$reg.log"; trace_state "$tmp/trace-$reg.log" "$pc" >"$tmp/state-$reg.txt"; [ "$(wc -l <"$tmp/state-$reg.txt")" = 84 ] || { echo "FAIL LATX trace state count for YMM$reg" >&2; exit 1; }; cmp "$expected/state-ymm$reg.txt" "$tmp/state-$reg.txt"; done; for n in $fault_cases; do run_case "$latx" "$probe" "$n" "$tmp/$n.bin" "$tmp/$n.status" "$tmp/$n.log"; check_fault "$tmp/$n.bin" "$tmp/$n.status"; cmp "$expected/$n.bin" "$tmp/$n.bin"; cmp "$expected/$n.status" "$tmp/$n.status"; trace_state "$tmp/$n.log" "$pc" >"$tmp/$n.state"; exp=$(od -An -v -tx8 -j32 -N16 "$expected/$n.bin" | awk '{print $1, $2}'); got=$(awk '{print $3, $4}' "$tmp/$n.state"); [ "$got" = "$exp" ] || { echo "FAIL $n changed YMM15 high: $got" >&2; exit 1; }; done; check_source "$source"; check_host "$latx"; echo "PASS vxorpd XMM/YMM register, memory, alias, flags/MXCSR, canary and fault differential";;
*) usage;; esac
