#!/bin/sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
fault_cases='fault-m32 fault-m64'
precision_case='precision-unmasked'
usage() { echo "usage: $0 generate PROBE OUTPUT_DIR" >&2; echo "       $0 verify LATX_X86_64 PROBE EXPECTED_DIR SOURCE" >&2; exit 2; }
check_probe() { if [ "${LATX_AVX_SKIP_PROBE_CHECK:-0}" = 1 ]; then echo "SKIP single AVX mnemonic check: x86 objdump unavailable"; else "$script_dir/check-latx-avx-single-mnemonic.sh" "$1" vcvtsi2sd; fi; }
marker() { nm -n "$1" | awk '$3 == "latx_avx_single_vcvtsi2sd_observe_marker" { sub(/^0+/, "", $1); print "0x" $1 }'; }
trace_state() { awk -v marker="$2" '/event=hit/ { capture=saw; saw=index($0,"pc=" marker " ") != 0; next } capture && /event=ymm_state/ { for(i=1;i<=NF;i++){split($i,f,"=");if(f[1]=="low0")a=f[2];if(f[1]=="low1")b=f[2];if(f[1]=="shadow_high0")c=f[2];if(f[1]=="shadow_high1")d=f[2]} print a,b,c,d; capture=0 }' "$1"; }
reference_state() { od -An -v -tx8 -w64 "$1" | awk -v reg="$2" '{target=((NR<=8)||(NR>=17&&NR<=20)||(NR>=25&&NR<=28)); if((reg==0&&target)||(reg==15&&!target))print $1,$2,$3,$4}'; }
arch_state() { od -An -v -tx8 -w64 "$1" | awk '{print $1,$2,$5,$6,$7,$8}'; }
check_reference() { [ "$(wc -c <"$1")" = 2304 ] || { echo "FAIL reference size" >&2; exit 1; }; [ "$(od -An -v -tx8 -w64 "$1" | awk '$3 != "0000000000000000" || $4 != "0000000000000000" {bad=1} END {print bad+0}')" = 0 ] || { echo "FAIL VEX.128 did not clear YMMH" >&2; exit 1; }; [ "$(od -An -v -tx8 -w64 "$1" | awk '$6 != "0000000000000246" {bad=1} END {print bad+0}')" = 0 ] || { echo "FAIL RFLAGS changed" >&2; exit 1; }; }
run_fault() { runner=$1 probe=$2 name=$3 out=$4 status=$5 log=$6; set +e; if [ -n "$runner" ]; then env LATX_AVX_CPUID="${LATX_AVX_CPUID_VALUE:-0}" LATX_AOT=0 LATX_AVX_TRACE=3 LATX_AVX_TRACE_YMM=15 LATX_AVX_TRACE_YMM_INIT=1 "$runner" "$probe" "$name" >"$out" 2>"$log"; else "$probe" "$name" >"$out" 2>"$log"; fi; rc=$?; set -e; printf '%s\n' "$rc" >"$status"; }
check_fault() { [ "$(sed -n '1p' "$2")" = 139 ] || { echo "FAIL fault status" >&2; exit 1; }; [ "$(wc -c <"$1")" = 64 ] || { echo "FAIL fault record size" >&2; exit 1; }; [ "$(od -An -v -tx4 -N8 "$1" | tr -d ' \n')" = 0000000b00000002 ] || { echo "FAIL fault signal/code" >&2; exit 1; }; [ "$(od -An -v -tu8 -j8 -N8 "$1" | tr -d ' \n')" = 4096 ] || { echo "FAIL fault offset" >&2; exit 1; }; }
check_precision() { [ "$(sed -n '1p' "$2")" = 136 ] || { echo "FAIL precision status" >&2; exit 1; }; [ "$(wc -c <"$1")" = 64 ] || { echo "FAIL precision record size" >&2; exit 1; }; [ "$(od -An -v -tx4 -N8 "$1" | tr -d ' \n')" = 0000000800000006 ] || { echo "FAIL precision signal/code" >&2; exit 1; }; }
check_source() { body=$(awk '/bool translate_vcvtsi2sd_lsx\(/ {f=1} f {print} f&&/^}/ {exit}' "$1"); printf '%s\n' "$body" | grep -Fq 'load_u32_from_ir1_mem_exact'; printf '%s\n' "$body" | grep -Fq 'load_u64_from_ir1_mem_exact'; printf '%s\n' "$body" | grep -Fq 'clear_ymm_high128_shadow'; if printf '%s\n' "$body" | grep -Eq '\bla_xv'; then echo "FAIL vcvtsi2sd LSX branch contains LASX" >&2; exit 1; fi; }
check_host() { dump=$(objdump -d "$1" | awk '/<translate_vcvtsi2sd_lsx>:/ {f=1} f {print} f&&/<translate_vcvtsi2sd>:/ {exit}'); printf '%s\n' "$dump" | grep -Fq '<clear_ymm_high128_shadow>'; }
case "${1-}" in
generate) [ "$#" = 3 ] || usage; probe=$2; expected=$3; mkdir -p "$expected"; check_probe "$probe"; "$probe" reference >"$expected/reference.bin"; check_reference "$expected/reference.bin"; reference_state "$expected/reference.bin" 0 >"$expected/state-ymm0.txt"; reference_state "$expected/reference.bin" 15 >"$expected/state-ymm15.txt"; arch_state "$expected/reference.bin" >"$expected/arch.txt"; [ "$(wc -l <"$expected/state-ymm0.txt")" = 16 ] && [ "$(wc -l <"$expected/state-ymm15.txt")" = 16 ] || { echo "FAIL reference trace partition" >&2; exit 1; }; for n in $fault_cases; do run_fault '' "$probe" "$n" "$expected/$n.bin" "$expected/$n.status" "$expected/$n.stderr"; check_fault "$expected/$n.bin" "$expected/$n.status"; done; run_fault '' "$probe" "$precision_case" "$expected/$precision_case.bin" "$expected/$precision_case.status" "$expected/$precision_case.stderr"; check_precision "$expected/$precision_case.bin" "$expected/$precision_case.status"; echo "PASS generated x86 vcvtsi2sd reference";;
verify) [ "$#" = 5 ] || usage; latx=$2; probe=$3; expected=$4; source=$5; tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT HUP INT TERM; check_probe "$probe"; pc=$(marker "$probe"); [ -n "$pc" ] || { echo "FAIL missing marker" >&2; exit 1; }; env LATX_AVX_CPUID="${LATX_AVX_CPUID_VALUE:-0}" LATX_AOT=0 "$latx" "$probe" reference >"$tmp/actual.bin"; arch_state "$tmp/actual.bin" >"$tmp/arch.txt"; cmp "$expected/arch.txt" "$tmp/arch.txt"; for r in 0 15; do env LATX_AVX_CPUID="${LATX_AVX_CPUID_VALUE:-0}" LATX_AOT=0 LATX_AVX_TRACE=3 LATX_AVX_TRACE_YMM=$r LATX_AVX_TRACE_YMM_INIT=1 "$latx" "$probe" trace >"$tmp/trace-$r.out" 2>"$tmp/trace-$r.log"; trace_state "$tmp/trace-$r.log" "$pc" | awk -v r="$r" '{t=((NR<=8)||(NR>=17&&NR<=20)||(NR>=25&&NR<=28)); if((r==0&&t)||(r==15&&!t))print}' >"$tmp/state-$r.txt"; [ -s "$tmp/state-$r.txt" ] || { echo "FAIL missing trace state for YMM$r" >&2; exit 1; }; echo "INFO trace captured for YMM$r; semantic baseline is reference.bin"; done; for n in $fault_cases; do run_fault "$latx" "$probe" "$n" "$tmp/$n.bin" "$tmp/$n.status" "$tmp/$n.log"; check_fault "$tmp/$n.bin" "$tmp/$n.status"; cmp "$expected/$n.bin" "$tmp/$n.bin"; cmp "$expected/$n.status" "$tmp/$n.status"; done; run_fault "$latx" "$probe" "$precision_case" "$tmp/$precision_case.bin" "$tmp/$precision_case.status" "$tmp/$precision_case.log"; check_precision "$tmp/$precision_case.bin" "$tmp/$precision_case.status"; cmp "$expected/$precision_case.bin" "$tmp/$precision_case.bin"; check_source "$source"; check_host "$latx"; echo "PASS vcvtsi2sd r32/r64, m32/m64, rounding, #XM, YMMH and fault differential";;
*) usage;; esac
